import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Download, Headphones, Database, GitBranch, MonitorSmartphone } from "lucide-react";
import { Reveal } from "@/components/motion/reveal";
import { InterfaceIllustration } from "@/components/editorial/interface-illustration";
import { ProjectSpread } from "@/components/editorial/project-spread";
import { CurvedArrow, FolderMark, IrregularStar, Sparkles, Tape } from "@/components/editorial/motifs";
import { capabilities } from "@/src/content/capabilities";
import { experience } from "@/src/content/experience";
import { projects } from "@/src/content/projects";
import { isLocale, siteConfig } from "@/src/content/site-config";

export default async function Home({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: raw } = await params; const locale = isLocale(raw) ? raw : "en"; const fr=locale === "fr";
  const jsonLd={ "@context":"https://schema.org", "@type":"Person", name:siteConfig.name, jobTitle:siteConfig.title, address:{"@type":"PostalAddress",addressLocality:"Bafoussam",addressCountry:"CM"}, sameAs:[siteConfig.linkedin] };
  return <main id="main" className="editorial-home"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}} />
    <section id="home" className="editorial-hero"><div className="editorial-inner hero-editorial"><div className="hero-statement"><Reveal><span className="scribble-label">{fr?"bonjour, moi c’est justice":"hello, i’m justice"}</span><h1>{fr?<>je construis des systèmes numériques<br/><em>qui rendent le travail plus clair.</em></>:<>i build digital systems<br/><em>that make work clearer.</em></>}</h1></Reveal><Reveal delay={.12}><p>{fr?"Développeur Frontend & Concepteur de Solutions Numériques basé à Bafoussam, Cameroun.":"Frontend Developer & Digital Solutions Builder based in Bafoussam, Cameroon."}</p><div className="editorial-actions"><Link href="#work">{fr?"Voir mes projets":"See my work"}<ArrowRight/></Link><Link href={`/${locale}/cv`}>{fr?"Ouvrir mon CV":"Open my CV"}<Download/></Link></div></Reveal></div><Reveal className="portrait-polaroid" delay={.22}><Tape/><Image priority src="/images/justice-portrait.jpg" alt="Portrait of Yong Justice Numfor" fill sizes="220px"/><span>Yong Justice / Bafoussam</span></Reveal><Reveal className="hero-snapshot snapshot-one" delay={.3}><InterfaceIllustration type="case" compact/></Reveal><Reveal className="hero-snapshot snapshot-two" delay={.38}><InterfaceIllustration type="archive" compact/></Reveal><IrregularStar className="hero-star"/><Sparkles className="hero-sparkles"/><CurvedArrow className="hero-arrow"/><div className="hero-note"><b>English + Français</b><span>{fr?"Disponible à distance + mobilité":"Remote + relocation open"}</span></div></div></section>
    <section id="about" className="editorial-section cream-section about-editorial"><div className="editorial-inner"><Reveal><div className="editorial-title"><span>01 / {fr?"profil":"about"}</span><h2>{fr?"à propos de moi":"about me"}</h2><IrregularStar/></div></Reveal><div className="about-grid"><Reveal><p className="about-lead">{fr?"Je suis particulièrement engagé lorsque la technologie doit rendre le travail réel plus simple à comprendre, organiser et accomplir.":"I’m most engaged when technology has to make real work easier to understand, organise, and complete."}</p><p>{fr?"Mon expérience relie les interfaces frontend à la gestion documentaire, aux opérations clients, à la qualité des données et au support informatique. Cette perspective m’aide à concevoir pour la personne qui utilisera le système chaque jour.":"My experience connects frontend interfaces with digital records, customer operations, data quality, and IT support. That perspective helps me design for the person who will use the system every day."}</p></Reveal><div className="project-bag"><span className="scribble-label">{fr?"ce que j’apporte à un projet":"what I bring to a project"}</span><div className="bag-object browser-object"><MonitorSmartphone/><b>responsive UI</b></div><div className="bag-object folder-object"><FolderMark/><b>clear records</b></div><div className="bag-object support-object"><Headphones/><b>user support</b></div><div className="bag-object data-object"><Database/><b>structured data</b></div><div className="bag-object git-object"><GitBranch/><b>documented delivery</b></div><CurvedArrow/></div></div></div></section>
    <section id="skills" className="editorial-section mint-section skills-editorial"><div className="editorial-inner"><Reveal><div className="editorial-title pale-title"><span>02 / TOOLKIT</span><h2>{fr?"compétences en pratique":"skills in practice"}</h2><IrregularStar/></div></Reveal><div className="skill-clusters">{capabilities[locale].map((item,i)=><Reveal key={item.name} delay={i*.06}><article><span>0{i+1}</span><h3>{item.name}</h3><p>{item.description}</p><small>{item.evidence}</small></article></Reveal>)}</div><div className="skill-evidence"><InterfaceIllustration type="archive" compact/><p>{fr?"Les outils ne sont pas des trophées. Je les choisis pour structurer l’information, réduire la friction et livrer un système maintenable.":"Tools are not trophies. I choose them to structure information, reduce friction, and deliver a maintainable system."}</p><Sparkles/></div></div></section>
    <section id="experience" className="editorial-section cream-section experience-editorial"><div className="editorial-inner"><Reveal><div className="editorial-title"><span>03 / RECORD</span><h2>{fr?"expérience":"experience"}</h2><IrregularStar/></div></Reveal><div className="experience-spread">{experience[locale].map((item,i)=><Reveal key={item.role} delay={i*.06}><article><span>{item.period}</span><h3>{item.role}</h3><p>{item.organisation}</p><small>{item.location}</small><p>{item.points[0]}</p></article></Reveal>)}</div><Link className="editorial-link" href={`/${locale}/profile`}>{fr?"Voir le profil complet":"Read the full profile"}<ArrowRight/></Link></div></section>
    <div id="work">{projects.filter(p=>p.hasCaseStudy).map((project,i)=><ProjectSpread key={project.slug} project={project} locale={locale} order={i+1}/>)}</div>
    <section id="contact" className="editorial-section cream-section contact-editorial"><div className="editorial-inner"><IrregularStar/><Reveal><span className="scribble-label">05 / CONTACT</span><h2>{fr?"construisons quelque chose d’utile ensemble.":"let’s build something useful together."}</h2><p>{fr?"Disponible pour des opportunités frontend, digitalisation, opérations IT, data et support technologique client.":"Available for frontend, digitalisation, IT operations, data, and customer-technology opportunities."}</p><div className="contact-links"><a href={`mailto:${siteConfig.email}`}>Email<ArrowRight/></a><a href={siteConfig.linkedin}>LinkedIn<ArrowRight/></a><a href={siteConfig.whatsapp}>WhatsApp<ArrowRight/></a><Link href={`/${locale}/contact`}>{fr?"Tous les contacts":"All contact details"}<ArrowRight/></Link></div><small>Bafoussam, Cameroon · English + Français · Remote + relocation open</small></Reveal></div></section>
  </main>;
}
