import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ClipboardCheck, Database, Download, FileStack, GitBranch, Headphones, MonitorSmartphone, Settings, UsersRound } from "lucide-react";
import { Reveal } from "@/components/motion/reveal";
import { InterfaceIllustration } from "@/components/editorial/interface-illustration";
import { ProjectSpread } from "@/components/editorial/project-spread";
import { CurvedArrow, FolderMark, IrregularStar, Sparkles, Tape } from "@/components/editorial/motifs";
import { capabilities } from "@/src/content/capabilities";
import { experience } from "@/src/content/experience";
import { projects } from "@/src/content/projects";
import { isLocale, siteConfig } from "@/src/content/site-config";

export default async function Home({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: raw } = await params; const locale = isLocale(raw) ? raw : "en"; const fr=locale === "fr";
  const jsonLd={ "@context":"https://schema.org", "@type":"Person", name:siteConfig.name, jobTitle:siteConfig.title, address:{"@type":"PostalAddress",addressLocality:"Bafoussam",addressCountry:"CM"}, sameAs:[siteConfig.linkedin] };
  return <main id="main" className="editorial-home"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}} />
    <section id="home" className="editorial-hero"><div className="editorial-inner hero-editorial"><div className="hero-statement"><Reveal><span className="scribble-label">{fr?"spécialiste IT & solutions numériques":"IT & Digital Solutions Specialist"}</span><h1>{fr?<>je crée des technologies utiles,<br/><em>j’aide les utilisateurs et simplifie le travail.</em></>:<>i build useful technology,<br/><em>support people, and make work simpler.</em></>}</h1></Reveal><Reveal delay={.12}><p>{fr?"Je combine technologie, développement d’applications web, support IT, service client et expérience opérationnelle pour créer des solutions pratiques et aider chacun à utiliser efficacement les outils numériques.":"I combine technology, web application development, IT support, customer service, and operational experience to build practical digital solutions and help people use technology effectively."}</p><span className="hero-location">{fr?"Basé à Bafoussam, Cameroun — disponible à distance, sur site et pour la mobilité.":"Based in Bafoussam, Cameroon — available for remote, on-site, and relocation opportunities."}</span><div className="editorial-actions"><Link href="#work">{fr?"Voir mes projets":"See my work"}<ArrowRight/></Link><Link href={`/${locale}/cv`}>{fr?"Ouvrir mon CV":"Open my CV"}<Download/></Link></div></Reveal></div><Reveal className="portrait-polaroid" delay={.22}><Tape/><Image priority src="/images/justice-portrait.jpg" alt="Portrait of Yong Justice Numfor" fill sizes="220px"/><span>Yong Justice / Bafoussam</span></Reveal><Reveal className="hero-snapshot snapshot-one" delay={.3}><InterfaceIllustration type="case" compact/></Reveal><Reveal className="hero-snapshot snapshot-two" delay={.38}><InterfaceIllustration type="archive" compact/></Reveal><IrregularStar className="hero-star"/><Sparkles className="hero-sparkles"/><CurvedArrow className="hero-arrow"/><div className="hero-note"><b>English + Français</b><span>{fr?"Technologie · Support · Opérations":"Technology · Support · Operations"}</span></div></div></section>
    <section id="about" className="editorial-section cream-section about-editorial"><div className="editorial-inner"><Reveal><div className="editorial-title"><span>01 / {fr?"profil":"about"}</span><h2>{fr?"à propos de moi":"about me"}</h2><IrregularStar/></div></Reveal><div className="about-grid"><Reveal><p className="about-lead">{fr?"Je construis des outils numériques, j’accompagne les utilisateurs et j’aide les opérations à fonctionner plus clairement.":"I build digital tools, support users, and help operations work more clearly."}</p><p>{fr?"Yong Justice Numfor est spécialiste IT et solutions numériques, avec une expérience en développement d’applications web, support technique, service client, organisation des données, digitalisation et processus opérationnels. Il conçoit des outils responsives, aide les utilisateurs à résoudre des problèmes techniques et de service, et transforme les besoins métier en solutions claires et utilisables.":"Yong Justice Numfor is an IT and Digital Solutions Specialist with experience across web application development, technical support, customer service, data organisation, digitalisation, and operational processes. He builds responsive digital tools, helps users resolve technical and service-related problems, and turns practical business needs into clear, usable solutions."}</p><p>{fr?"Son expérience client renforce sa compréhension de la communication, du suivi, de la précision, des besoins utilisateurs et de la qualité de service.":"His customer-facing background brings a strong understanding of communication, follow-up, accuracy, user needs, and service quality."}</p></Reveal><div className="project-bag"><span className="scribble-label">{fr?"ce que j’apporte à un projet":"what I bring to a project"}</span><div className="bag-object browser-object"><MonitorSmartphone/><b>web applications</b></div><div className="bag-object folder-object"><FolderMark/><b>digitalisation</b></div><div className="bag-object support-object"><Headphones/><b>technical support</b></div><div className="bag-object data-object"><Database/><b>data & reporting</b></div><div className="bag-object git-object"><GitBranch/><b>reliable delivery</b></div><div className="bag-object customer-object"><UsersRound/><b>{fr?"opérations clients":"customer operations"}</b></div><div className="bag-object documents-object"><FileStack/><b>{fr?"gestion documentaire":"document workflows"}</b></div><div className="bag-object process-object"><ClipboardCheck/><b>{fr?"amélioration des processus":"process improvement"}</b></div><div className="bag-object tools-object"><Settings/><b>{fr?"résolution de problèmes":"troubleshooting"}</b></div><CurvedArrow/></div></div></div></section>
    <section id="skills" className="editorial-section mint-section skills-editorial"><div className="editorial-inner"><Reveal><div className="editorial-title pale-title"><span>02 / TOOLKIT</span><h2>{fr?"compétences en pratique":"skills in practice"}</h2><IrregularStar/></div></Reveal><div className="skill-clusters">{capabilities[locale].map((item,i)=><Reveal key={item.name} delay={i*.06}><article><span>0{i+1}</span><h3>{item.name}</h3><p>{item.description}</p><small>{item.evidence}</small></article></Reveal>)}</div><div className="skill-evidence"><InterfaceIllustration type="archive" compact/><p>{fr?"Les outils ne sont pas des trophées. Je les choisis pour structurer l’information, réduire la friction et livrer un système maintenable.":"Tools are not trophies. I choose them to structure information, reduce friction, and deliver a maintainable system."}</p><Sparkles/></div></div></section>
    <section id="experience" className="editorial-section cream-section experience-editorial"><div className="editorial-inner"><Reveal><div className="editorial-title"><span>03 / RECORD</span><h2>{fr?"expérience":"experience"}</h2><IrregularStar/></div></Reveal><div className="experience-spread">{experience[locale].map((item,i)=><Reveal key={item.role} delay={i*.06}><article><span>{item.period}</span><h3>{item.role}</h3><p>{item.organisation}</p><small>{item.location}</small><p>{item.points[0]}</p></article></Reveal>)}</div><Link className="editorial-link" href={`/${locale}/profile`}>{fr?"Voir le profil complet":"Read the full profile"}<ArrowRight/></Link></div></section>
    <div id="work">{projects.filter(p=>p.hasCaseStudy).map((project,i)=><ProjectSpread key={project.slug} project={project} locale={locale} order={i+1}/>)}</div>
    <section id="contact" className="editorial-section cream-section contact-editorial"><div className="editorial-inner"><IrregularStar/><Reveal><span className="scribble-label">05 / CONTACT</span><h2>{fr?"construisons, accompagnons et améliorons ensemble.":"let’s build, support, and improve something useful."}</h2><p>{fr?"Disponible pour des opportunités en solutions numériques, support IT, applications web, assistance client, opérations, digitalisation et données.":"Available for digital solutions, IT support, web applications, customer support, operations, digitalisation, and data-focused opportunities."}</p><div className="contact-links"><a href={`mailto:${siteConfig.email}`}>Email<ArrowRight/></a><a href={siteConfig.linkedin}>LinkedIn<ArrowRight/></a><a href={siteConfig.whatsapp}>WhatsApp<ArrowRight/></a><Link href={`/${locale}/contact`}>{fr?"Tous les contacts":"All contact details"}<ArrowRight/></Link></div><small>Bafoussam, Cameroon · English + Français · Remote · On-site · Relocation</small></Reveal></div></section>
  </main>;
}
